# Generated by Django 3.1.7 on 2021-03-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='note_text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст записи'),
        ),
    ]
